- type: gameMapPool
  id: DefaultMapPool
  maps:
   - Comoss
   - Frigid_Coast
   
- type: gameMapPool
  id: CP14Expedition
  maps:
   - GrasslandExpansion

- type: gameMapPool
  id: DeathMatchMapPool
  maps:
  - MeteorArena
